version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8080

  database:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017