version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/files/index.js
    ports:
      - 3000:8080

  database:
    image: mongo:5
    ports:
      - 27017:27017