version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/files/index.js
      - ./swagger/tokens.swagger.js:/files/swagger/tokens.swagger.js
      - ./swagger/user.swagger.js:/files/swagger/user.swagger.js
      - ./swagger/users.swagger.js:/files/swagger/users.swagger.js
      - ./swagger/starbucks.swagger.js:/files/swagger/starbucks.swagger.js
    ports:
      - 3000:8080

  database:
    image: mongo:5
    ports:
      - 27017:27017