version: "3.7"

services:
  api-gateway:
    image: nginx:latest
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth/src:/auth-service/src
      #Docker에서는 Dockerfile에서 auth-service폴더로 만들어줌.

  stock-service:
    build:
      context: ./services/stock
      dockerfile: Dockerfile
    