version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    env_file:
      - ./.env
    ports:
      - 3000:3000

  # database:
  #   image: mysql:latest
  #   environment:
  #       MYSQL_DATABASE: 'mydocker03'
  #       MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306